FROM golang

COPY ./ ./app

COPY ./server.sh ./start.sh
COPY ./web.sh ./web.sh
RUN cd app && ls -al && \
    apt update && \
    go mod tidy && \
    apt install -y supervisor

EXPOSE 8081
COPY ./supervisor.conf /etc/supervisord.conf
ENTRYPOINT ["/usr/bin/supervisord"]
